include:  package:lint/analysis_options.yaml

analyzer:
  exclude: 
    - lib/generated/**
    - lib/**.g.dart
    - lib/**.freezed.dart
  errors:
    missing_return: error
    must_be_immutable: error
    must_call_super: error
    invalid_use_of_protected_member: error
    parameter_assignments: error
    sort_unnamed_constructors_first: ignore
    